openapi: 3.2.0
info:
  title: iNaturalist Flags API
  description: '# https://api.inaturalist.org/v1/


    iNaturalist is a global community of

    naturalists, scientists, and members of the public sharing over a million

    wildlife sightings to teach one another about the natural world while

    creating high quality citizen science data for science and conservation.'
  version: 1.3.0
servers:
- url: /v1
tags:
- name: Flags
  description: Create, update, and delete flags
paths:
  /flags:
    post:
      summary: Flag Create
      description: 'Create a flag. To create a custom flag beyond the standard `spam` and

        `inappropriate` flags, set `flag` to `other` and include a `flag_explanation`'
      tags:
      - Flags
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostFlag'
        description: Flag object
      operationId: postFlags
      x-operation-id-source: derived
  /flags/{id}:
    put:
      summary: Flag Update
      description: Update a flag. Generally only used to resolve the flag.
      parameters:
      - $ref: '#/components/parameters/path_id'
      tags:
      - Flags
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutFlag'
      operationId: putFlagsById
      x-operation-id-source: derived
    delete:
      summary: Flag Delete
      description: Delete a flag
      parameters:
      - $ref: '#/components/parameters/path_id'
      tags:
      - Flags
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      operationId: deleteFlagsById
      x-operation-id-source: derived
components:
  schemas:
    PutFlag:
      type: object
      properties:
        flag:
          type: object
          properties:
            resolved:
              type: boolean
    PostFlag:
      type: object
      properties:
        flag:
          type: object
          properties:
            flaggable_type:
              type: string
              enum:
              - Comment
              - Identification
              - Message
              - Observation
              - Post
              - Taxon
            flaggable_id:
              type: integer
            flag:
              enum:
              - spam
              - inappropriate
              - other
        flag_explanation:
          type: string
  parameters:
    path_id:
      name: id
      in: path
      required: true
      description: ID of the record
      schema:
        type: integer
  securitySchemes:
    api_token:
      type: apiKey
      name: Authorization
      in: header
