openapi: 3.2.0
info:
  title: iNaturalist Polygon Tiles API
  description: '# https://api.inaturalist.org/v1/


    iNaturalist is a global community of

    naturalists, scientists, and members of the public sharing over a million

    wildlife sightings to teach one another about the natural world while

    creating high quality citizen science data for science and conservation.'
  version: 1.3.0
servers:
- url: /v1
tags:
- name: Polygon Tiles
  description: Place geometry and taxon range tiles
paths:
  /places/{place_id}/{zoom}/{x}/{y}.png:
    get:
      summary: Place Tiles
      description: 'Returns a PNG map tile representing the boundary of this place,

        following the XYZ tiling scheme'
      parameters:
      - $ref: '#/components/parameters/path_place_id'
      - $ref: '#/components/parameters/zoom'
      - $ref: '#/components/parameters/x'
      - $ref: '#/components/parameters/y'
      - $ref: '#/components/parameters/ttl'
      tags:
      - Polygon Tiles
      responses:
        '200':
          description: 'Returns a PNG map tile image

            '
      operationId: getPlacesByPlaceIdByZoomByX{y}Png
      x-operation-id-source: derived
  /taxon_places/{taxon_id}/{zoom}/{x}/{y}.png:
    get:
      summary: Taxon Place Tiles
      description: 'Returns a PNG map tile representing the boundaries of places this taxon

        is known to occur, following the XYZ tiling scheme'
      parameters:
      - $ref: '#/components/parameters/path_taxon_id'
      - $ref: '#/components/parameters/zoom'
      - $ref: '#/components/parameters/x'
      - $ref: '#/components/parameters/y'
      - $ref: '#/components/parameters/ttl'
      tags:
      - Polygon Tiles
      responses:
        '200':
          description: 'Returns a PNG map tile image

            '
      operationId: getTaxonPlacesByTaxonIdByZoomByX{y}Png
      x-operation-id-source: derived
  /taxon_ranges/{taxon_id}/{zoom}/{x}/{y}.png:
    get:
      summary: Taxon Range Tiles
      description: 'Returns a PNG map tile representing the range of this taxon, following

        the XYZ tiling scheme'
      parameters:
      - $ref: '#/components/parameters/path_taxon_id'
      - $ref: '#/components/parameters/zoom'
      - $ref: '#/components/parameters/x'
      - $ref: '#/components/parameters/y'
      - $ref: '#/components/parameters/tile_color'
      - $ref: '#/components/parameters/ttl'
      tags:
      - Polygon Tiles
      responses:
        '200':
          description: 'Returns a PNG map tile image

            '
      operationId: getTaxonRangesByTaxonIdByZoomByX{y}Png
      x-operation-id-source: derived
components:
  parameters:
    tile_color:
      name: color
      in: query
      description: 'Primary color to use in tile creation. Accepts common colors by string

        (e.g. `color=blue`), and accepts escaped color HEX codes

        (e.g. `color=%2386a91c`)

        '
      schema:
        type: string
    ttl:
      name: ttl
      in: query
      description: 'Set the `Cache-Control` HTTP header with this value as `max-age`, in

        seconds. This means subsequent identical requests will be cached on

        iNaturalist servers, and commonly within web browsers

        '
      schema:
        type: string
    path_place_id:
      name: place_id
      in: path
      required: true
      description: Place ID
      schema:
        type: integer
    y:
      name: y
      in: path
      required: true
      description: Y coordinate in the XYZ tiling scheme. Must be less than 2^zoom
      schema:
        type: integer
        minimum: 0
    path_taxon_id:
      name: taxon_id
      in: path
      required: true
      description: Taxon ID
      schema:
        type: integer
    zoom:
      name: zoom
      in: path
      required: true
      description: Zoom level. Z coordinate in the XYZ tiling scheme
      schema:
        type: integer
        maximum: 21
        minimum: 0
    x:
      name: x
      in: path
      required: true
      description: X coordinate in the XYZ tiling scheme. Must be less than 2^zoom
      schema:
        type: integer
        minimum: 0
  securitySchemes:
    api_token:
      type: apiKey
      name: Authorization
      in: header
