openapi: 3.2.0
info:
  title: iNaturalist Photos API
  description: '# https://api.inaturalist.org/v1/


    iNaturalist is a global community of

    naturalists, scientists, and members of the public sharing over a million

    wildlife sightings to teach one another about the natural world while

    creating high quality citizen science data for science and conservation.'
  version: 1.3.0
servers:
- url: /v1
tags:
- name: Photos
paths:
  /photos:
    post:
      summary: Photo Create
      description: Create a photo
      tags:
      - Photos
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: The photo
                  format: binary
      operationId: postPhotos
      x-operation-id-source: derived
components:
  securitySchemes:
    api_token:
      type: apiKey
      name: Authorization
      in: header
