openapi: 3.2.0
info:
  title: iNaturalist Posts API
  description: '# https://api.inaturalist.org/v1/


    iNaturalist is a global community of

    naturalists, scientists, and members of the public sharing over a million

    wildlife sightings to teach one another about the natural world while

    creating high quality citizen science data for science and conservation.'
  version: 1.3.0
servers:
- url: /v1
tags:
- name: Posts
  description: Fetch site and project posts
paths:
  /posts:
    get:
      summary: Posts Search
      description: Return journal posts from the iNaturalist site
      parameters:
      - $ref: '#/components/parameters/posts_login'
      - $ref: '#/components/parameters/posts_project_id'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/per_page'
      tags:
      - Posts
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      operationId: getPosts
      x-operation-id-source: derived
    post:
      summary: Post Create
      description: Create a post
      tags:
      - Posts
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPost'
        description: Post object
      operationId: postPosts
      x-operation-id-source: derived
  /posts/{id}:
    put:
      summary: Post Update
      description: Update a post
      parameters:
      - $ref: '#/components/parameters/path_id'
      tags:
      - Posts
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPost'
        description: Post object
      operationId: putPostsById
      x-operation-id-source: derived
    delete:
      summary: Post Delete
      description: Delete a post
      parameters:
      - $ref: '#/components/parameters/path_id'
      tags:
      - Posts
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      operationId: deletePostsById
      x-operation-id-source: derived
  /posts/for_user:
    get:
      summary: Posts For User
      description: 'Return journal posts from the iNaturalist site. If the user is logged-in,

        also return posts from projects the user is subscribed to'
      parameters:
      - name: newer_than
        in: query
        description: returns posts newer than the post with this ID
        schema:
          type: integer
      - name: older_than
        in: query
        description: returns posts older than the post with this ID
        schema:
          type: integer
      - $ref: '#/components/parameters/page'
      tags:
      - Posts
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      operationId: getPostsForUser
      x-operation-id-source: derived
components:
  parameters:
    path_id:
      name: id
      in: path
      required: true
      description: ID of the record
      schema:
        type: integer
    posts_project_id:
      name: project_id
      in: query
      description: Return posts from this project
      schema:
        type: integer
    page:
      name: page
      in: query
      description: Pagination `page` number
      schema:
        type: string
    posts_login:
      name: login
      in: query
      description: Return posts by this user
      schema:
        type: string
    per_page:
      name: per_page
      in: query
      description: 'Number of results to return in a `page`. The maximum value is generally

        200 unless otherwise noted

        '
      schema:
        type: string
  schemas:
    PostPost:
      type: object
      properties:
        commit:
          type: string
          example: Publish
        post:
          type: object
          properties:
            title:
              type: string
            body:
              type: string
            preferred_formatting:
              type: string
              example: simple
            user_id:
              type: number
            parent_id:
              type: number
            parent_type:
              type: string
              example: Project
  securitySchemes:
    api_token:
      type: apiKey
      name: Authorization
      in: header
