openapi: 3.2.0
info:
  title: iNaturalist Observation Photos API
  description: '# https://api.inaturalist.org/v1/


    iNaturalist is a global community of

    naturalists, scientists, and members of the public sharing over a million

    wildlife sightings to teach one another about the natural world while

    creating high quality citizen science data for science and conservation.'
  version: 1.3.0
servers:
- url: /v1
tags:
- name: Observation Photos
  description: Create and delete
paths:
  /observation_photos/{id}:
    put:
      summary: Observation Photo Update
      description: Update an observation photo
      parameters:
      - $ref: '#/components/parameters/path_id'
      tags:
      - Observation Photos
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                observation_photo[position]:
                  type: integer
                  description: Position in which the photo is displayed for the observation
                file:
                  type: string
                  description: The photo
                  format: binary
      operationId: putObservationPhotosById
      x-operation-id-source: derived
    delete:
      summary: Observation Photo Delete
      description: Delete an observation photo
      parameters:
      - $ref: '#/components/parameters/path_id'
      tags:
      - Observation Photos
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      operationId: deleteObservationPhotosById
      x-operation-id-source: derived
  /observation_photos:
    post:
      summary: Observation Photo Create
      description: Create an observation photo
      tags:
      - Observation Photos
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                observation_photo[observation_id]:
                  type: integer
                  description: Observation ID
                observation_photo[uuid]:
                  type: string
                  description: Observation UUID
                file:
                  type: string
                  description: The photo
                  format: binary
      operationId: postObservationPhotos
      x-operation-id-source: derived
components:
  parameters:
    path_id:
      name: id
      in: path
      required: true
      description: ID of the record
      schema:
        type: integer
  securitySchemes:
    api_token:
      type: apiKey
      name: Authorization
      in: header
