openapi: 3.2.0
info:
  title: iNaturalist Project Observations API
  description: '# https://api.inaturalist.org/v1/


    iNaturalist is a global community of

    naturalists, scientists, and members of the public sharing over a million

    wildlife sightings to teach one another about the natural world while

    creating high quality citizen science data for science and conservation.'
  version: 1.3.0
servers:
- url: /v1
tags:
- name: Project Observations
  description: Create, update, and delete
paths:
  /project_observations/{id}:
    put:
      summary: Project Observation Update
      description: Update a project observation
      parameters:
      - $ref: '#/components/parameters/path_id'
      tags:
      - Project Observations
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectObservation'
        description: Comment object
      operationId: putProjectObservationsById
      x-operation-id-source: derived
    delete:
      summary: Project Observation Delete
      description: Delete a project observation
      parameters:
      - $ref: '#/components/parameters/path_id'
      tags:
      - Project Observations
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      operationId: deleteProjectObservationsById
      x-operation-id-source: derived
  /project_observations:
    post:
      summary: Project Observation Create
      description: Add an observation to a project
      tags:
      - Project Observations
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostProjectObservation'
        description: ProjectObservation object
      operationId: postProjectObservations
      x-operation-id-source: derived
components:
  schemas:
    PostProjectObservation:
      type: object
      properties:
        project_id:
          type: integer
        observation_id:
          type: integer
    UpdateProjectObservation:
      type: object
      properties:
        project_observation:
          type: object
          properties:
            project_id:
              type: integer
            observation_id:
              type: integer
            prefers_curator_coordinate_access:
              type: boolean
  parameters:
    path_id:
      name: id
      in: path
      required: true
      description: ID of the record
      schema:
        type: integer
  securitySchemes:
    api_token:
      type: apiKey
      name: Authorization
      in: header
