openapi: 3.2.0
info:
  title: iNaturalist Comments API
  description: '# https://api.inaturalist.org/v1/


    iNaturalist is a global community of

    naturalists, scientists, and members of the public sharing over a million

    wildlife sightings to teach one another about the natural world while

    creating high quality citizen science data for science and conservation.'
  version: 1.3.0
servers:
- url: /v1
tags:
- name: Comments
  description: Create, update, and delete
paths:
  /comments:
    post:
      summary: Comment Create
      description: Create a comment
      tags:
      - Comments
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostComment'
        description: Comment object
      operationId: postComments
      x-operation-id-source: derived
  /comments/{id}:
    put:
      summary: Comment Update
      description: Update a comment
      parameters:
      - $ref: '#/components/parameters/path_id'
      tags:
      - Comments
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostComment'
        description: Comment object
      operationId: putCommentsById
      x-operation-id-source: derived
    delete:
      summary: Comment Delete
      description: Delete a comment
      parameters:
      - $ref: '#/components/parameters/path_id'
      tags:
      - Comments
      security:
      - api_token: []
      responses:
        '200':
          description: OK
      operationId: deleteCommentsById
      x-operation-id-source: derived
components:
  parameters:
    path_id:
      name: id
      in: path
      required: true
      description: ID of the record
      schema:
        type: integer
  schemas:
    PostComment:
      type: object
      properties:
        comment:
          type: object
          properties:
            parent_type:
              type: string
              enum:
              - Observation
              - ListedTaxon
              - AssessmentSection
              - ObservationField
              - Post
              - TaxonChange
            parent_id:
              type: integer
            body:
              type: string
  securitySchemes:
    api_token:
      type: apiKey
      name: Authorization
      in: header
